spring.application.name=appstock

server.port=8081

spring.data.rest.base-path=/api

spring.profiles.active=prod

spring.web.locale=es_ES
spring.web.locale-resolver=fixed

spring.application.version=1.0

spring.jpa.hibernate.ddl-auto=update